# Generated by Django 3.2 on 2021-04-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_token', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=11)),
                ('device_model', models.CharField(max_length=11)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('app', models.CharField(max_length=11)),
                ('version', models.CharField(max_length=11)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=11)),
                ('longitude', models.CharField(max_length=11)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('data', models.JSONField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
        ),
    ]
