# Generated by Django 3.2 on 2021-04-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='data',
            field=models.TextField(),
        ),
    ]
